import type { AssessmentInput } from "@/lib/assessment/AssessmentInput";
import type { AssessmentResult } from "@/lib/assessment/AssessmentResult";
import { getExplainability } from "@/lib/assessment/getExplainability";

/**
 * Generate a Markdown report of the assessment result.
 * This can be used for PDF generation or display.
 * 
 * @param input - The original input used for assessment
 * @param result - The output result from the assessment engine
 * @returns Markdown string of the full report
 */
export function generateAssessmentReport(
    input: AssessmentInput,
    result: AssessmentResult
): string {
    const { checkEvidenceMap } = getExplainability(input, result);
    const date = new Date(result.generatedAt).toLocaleDateString("en-GB", {
        year: 'numeric', month: 'long', day: 'numeric'
    });

    const lines: string[] = [];

    // Header
    lines.push(`# Assessment Report`);
    lines.push(`**Case ID:** ${input.caseId}`);
    lines.push(`**Date:** ${date}`);
    lines.push(`**Dispute Type:** ${input.disputeType || "Unknown"}`);
    lines.push("");

    // Verdict
    lines.push("## Verdict");
    lines.push(`### ${result.verdict}`);
    if (result.reasons.length > 0) {
        lines.push("");
        for (const reason of result.reasons) {
            lines.push(`- ${reason}`);
        }
    }
    lines.push("");

    // Checks Analysis
    lines.push("## Analysis");

    // Group checks if needed, currently list flat
    for (const check of result.checks) {
        const icon = check.passed ? "✅" : "❌";
        lines.push(`### ${icon} ${check.label}`);
        lines.push(check.rationale);

        // Add citations if present
        if (check.citations && check.citations.length > 0) {
            lines.push("");
            lines.push("**Authorities:**");
            for (const cite of check.citations) {
                const urlPart = cite.url ? ` ([Link](${cite.url}))` : "";
                lines.push(`- *${cite.ref}*: ${cite.text || "Relevant section"}${urlPart}`);
            }
        }
        lines.push("");
    }

    // Evidence Summary
    lines.push("## Evidence Reviewed");
    if (input.evidence.docs.length === 0) {
        lines.push("No documents were uploaded for this assessment.");
    } else {
        for (const doc of input.evidence.docs) {
            const provenance = doc.provenance || "Unknown Source";
            lines.push(`- **${doc.filename || doc.id}** (${provenance})`);
        }
    }
    lines.push("");

    // Missing Info (if any)
    if (result.missingInfo.length > 0) {
        lines.push("## Missing Information");
        lines.push("The following critical information was unavailable:");
        for (const info of result.missingInfo) {
            lines.push(`- ${info}`);
        }
        lines.push("");
    }

    lines.push("---");
    lines.push("*Generated by Resolve Engine*");

    return lines.join("\n");
}
